Attribute VB_Name = "Module1"
Public FSO As New FileSystemObject
Public FileCount As Variant
Public FolderCount As Variant
Public FileCount1 As Variant
Public FileCount2 As Variant
Public FileCount3 As Variant
Public SubFolderCount1 As Variant
Public SubFolderCount2 As Variant
Public SubFolderCount3 As Variant
Public Folder1 As folder
Public Folder2 As folder
Public Folder3 As folder
Public Bytes1 As Currency
Public Bytes2 As Currency
Public Bytes3 As Currency
Public Kilobytes1 As Double
Public Kilobytes2 As Double
Public Kilobytes3 As Double
Public Megabytes1 As Double
Public Megabytes2 As Double
Public Megabytes3 As Double
Public Gigabytes1 As Double
Public Gigabytes2 As Double
Public Gigabytes3 As Double
